import "./globals.css";
import "@mantine/core/styles.css";
import '@mantine/dates/styles.css';
import '@mantine/charts/styles.css';
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { NextAuthProvider } from "@/components/Providers";
import { Toaster } from "react-hot-toast";
import { createTheme, MantineProvider } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

const theme = createTheme({
  /** Put your mantine theme override here */
});

export const metadata: Metadata = {
  title: "Tech News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <NextAuthProvider>
            <div className="lg:max-w-[900px] lg:px-16 mx-auto py-8 shadow-xl min-h-screen flex flex-col px-8">
              <Navbar />
              <div className="flex-auto">{children}</div>
              <Footer />
            </div>
            <Toaster />
          </NextAuthProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
